--- 
abstract: YUI for your CatalystX::CRUD view
author: 
  - Peter Karman, C<< <karman@cpan.org> >>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: CatalystX-CRUD-YUI
no_index: 
  directory: 
    - inc
    - t
recommends: 
  CatalystX::CRUD::Model::RDBO: 0.14
  CatalystX::CRUD::ModelAdapter::DBIC: 0.06
  DBIx::Class::RDBOHelpers: 0.05
  Rose::DBx::Object::MoreHelpers: 0.02
requires: 
  Catalyst::View::TT: 0
  CatalystX::CRUD: 0.3
  CatalystX::CRUD::Controller::RHTMLO: 0.17
  CatalystX::CRUD::View::Excel: 0.05
  Class::C3: 0
  JSON::XS: 2
  Path::Class: 0
  Rose::HTMLx::Form::Related: 0.07
  Scalar::Util: 0
  Template: 0
  Test::More: 0
  Text::Autoformat: 0
version: 0.004
