---
abstract: 'YUI for your CatalystX::CRUD view'
author:
  - 'Peter Karman, C<< <karman@cpan.org> >>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-CRUD-YUI
no_index:
  directory:
    - inc
    - t
recommends:
  CatalystX::CRUD::Model::RDBO: 0.16
  CatalystX::CRUD::ModelAdapter::DBIC: 0.07
  DBIx::Class::RDBOHelpers: 0.08
  Rose::DBx::Object::MoreHelpers: 0.06
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::View::TT: 0
  CatalystX::CRUD: 0.32
  CatalystX::CRUD::Controller::RHTMLO: 0.18
  CatalystX::CRUD::View::Excel: 0.06
  Class::C3: 0
  JSON::XS: 2.23
  Path::Class: 0
  Rose::HTMLx::Form::Related: 0.12
  Scalar::Util: 0
  Template: 0
  Template::Plugin::Handy: 0.002
  Test::More: 0
  Text::Autoformat: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.009
