---
abstract: 'YUI for your CatalystX::CRUD view'
author:
  - 'Peter Karman, C<< <karman@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-CRUD-YUI
no_index:
  directory:
    - inc
    - t
recommends:
  CatalystX::CRUD::Model::RDBO: 0.23
  CatalystX::CRUD::ModelAdapter::DBIC: 0.08
  DBIx::Class::RDBOHelpers: 0.08
  Rose::DBx::Object::MoreHelpers: 0.06
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::View::TT: 0
  CatalystX::CRUD: 0.53
  CatalystX::CRUD::Controller::RHTMLO: 0.19
  CatalystX::CRUD::View::Excel: 0.06
  Class::Inspector: 0
  Config::General: 0
  JSON::XS: 2.23
  MRO::Compat: 0
  Path::Class: 0
  Rose::HTMLx::Form::Related: 0.17
  Scalar::Util: 0
  Template: 0
  Template::Plugin::Autoformat: 0
  Template::Plugin::Handy: 0.002
  Test::More: 0
  Text::Autoformat: 0
  perl: 5.8.3
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=CatalystX-CRUD-YUI
  homepage: https://github.com/karpet/catalystx-crud-yui
  license: http://dev.perl.org/licenses/
  repository: https://github.com/karpet/catalystx-crud-yui
version: 0.029
